package com.hujiayucc.hook.hooker.sdk

import io.github.libxposed.api.XposedModuleInterface

/** 百度联盟 / 百青藤 */
object BaiQingTeng : SimpleSdkHooker() {
    override fun XposedModuleInterface.PackageReadyParam.onPackageReady() {
        hookClassMethods(
            "com.baidu.mobads.sdk.api.MobadsPermissionSettings",
            "setPermissionReadDeviceID",
            "setPermissionAppList",
            "setPermissionLocation",
            "setPermissionStorage",
            "setLimitPersonalAds"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.BDAdConfig",
            "init",
            "setAppsid",
            "setDebug",
            "setHttps",
            "setDialogFrame",
            "setLimitPersonalAds"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.SplashAd",
            "load",
            "loadAndShow",
            "show",
            "destroy",
            "isReady"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.RewardVideoAd",
            "load",
            "show",
            "destroy",
            "isReady"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.InterstitialAd",
            "loadAd",
            "showAd",
            "destroy",
            "isReady"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.ExpressInterstitialAd",
            "load",
            "show",
            "destroy",
            "isReady"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.BannerView",
            "loadAd",
            "destroy"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.FeedNative",
            "loadFeedAd",
            "loadPortraitVideoAd",
            "loadExpressAd"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.BaiduNativeManager",
            "loadFeedAd",
            "loadPortraitVideoAd",
            "loadExpressAd",
            "loadContentAd",
            "loadAd"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.BaiduNative",
            "makeRequest",
            "loadNativeAd",
            "loadNativeExpressAd",
            "loadFeedAd"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.XAdNativeResponse",
            "recordImpression",
            "handleClick",
            "registerViewForInteraction",
            "registerViewForInteraction2",
            "clearImpressionTaskWhenBack"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.NativeResponse",
            "recordImpression",
            "handleClick",
            "registerViewForInteraction",
            "registerViewForInteraction2",
            "clearImpressionTaskWhenBack"
        )
        hookClassMethods(
            "com.baidu.mobads.sdk.api.NativeCPUAdManager",
            "loadAd",
            "destroy"
        )
        listOf(
            "com.baidu.mobads.sdk.api.AppActivity",
            "com.baidu.mobads.sdk.api.MobRewardVideoActivity",
            "com.baidu.mobads.sdk.api.MobadsVideoActivity"
        ).forEach { activityClass ->
            hookClassMethods(activityClass, "onCreate", "onStart", "onResume")
        }
    }
}