package com.hujiayucc.hook.hooker.sdk

import io.github.libxposed.api.XposedModuleInterface

/** Google AdMob / Google Mobile Ads */
object GoogleAds : SimpleSdkHooker() {
    override fun XposedModuleInterface.PackageReadyParam.onPackageReady() {
        hookClassMethods(
            "com.google.android.gms.ads.MobileAds",
            "initialize",
            "setRequestConfiguration",
            "disableMediationAdapterInitialization",
            "registerRtbAdapter",
            "registerWebView",
            "registerCustomTabsSession",
            "startPreload",
            "putPublisherFirstPartyIdEnabled"
        )
        hookClassMethods(
            "com.google.android.gms.ads.BaseAdView",
            "loadAd",
            "destroy",
            "pause",
            "resume",
            "isLoading",
            "setAdUnitId"
        )
        hookClassMethods(
            "com.google.android.gms.ads.AdView",
            "loadAd",
            "destroy",
            "pause",
            "resume",
            "isLoading"
        )
        hookClassMethods(
            "com.google.android.gms.ads.admanager.AdManagerAdView",
            "loadAd",
            "destroy",
            "pause",
            "resume",
            "isLoading",
            "recordManualImpression"
        )
        hookClassMethods(
            "com.google.android.gms.ads.AdLoader",
            "loadAd",
            "loadAds",
            "isLoading"
        )
        hookClassMethods(
            "com.google.android.gms.ads.interstitial.InterstitialAd",
            "load",
            "show",
            "isAdAvailable",
            "pollAd"
        )
        hookClassMethods(
            "com.google.android.gms.ads.admanager.AdManagerInterstitialAd",
            "load",
            "show",
            "isAdAvailable",
            "pollAd"
        )
        hookClassMethods(
            "com.google.android.gms.ads.rewarded.RewardedAd",
            "load",
            "show",
            "isAdAvailable",
            "pollAd"
        )
        hookClassMethods(
            "com.google.android.gms.ads.rewardedinterstitial.RewardedInterstitialAd",
            "load",
            "show"
        )
        hookClassMethods(
            "com.google.android.gms.ads.appopen.AppOpenAd",
            "load",
            "show",
            "isAdAvailable",
            "pollAd"
        )
        listOf(
            "com.google.android.gms.ads.appopen.AppOpenAdPreloader",
            "com.google.android.gms.ads.interstitial.InterstitialAdPreloader",
            "com.google.android.gms.ads.rewarded.RewardedAdPreloader"
        ).forEach { preloaderClass ->
            hookClassMethods(preloaderClass, "start", "destroy", "destroyAll", "isAdAvailable", "pollAd")
        }
        hookClassMethods(
            "com.google.android.gms.ads.nativead.NativeAd",
            "destroy",
            "performClick",
            "recordImpression",
            "reportTouchEvent",
            "recordCustomClickGesture"
        )
        hookClassMethods(
            "com.google.android.gms.ads.formats.UnifiedNativeAd",
            "performClick",
            "recordImpression",
            "reportTouchEvent"
        )
        hookClassMethods(
            "com.google.android.gms.ads.nativead.NativeAdView",
            "setNativeAd",
            "destroy",
            "dispatchTouchEvent"
        )
        hookClassMethods(
            "com.google.android.gms.ads.h5.H5AdsRequestHandler",
            "handleH5AdsRequest",
            "shouldInterceptRequest",
            "clearAdObjects"
        )
        hookClassMethods(
            "com.google.android.gms.ads.h5.H5AdsWebViewClient",
            "clearAdObjects"
        )
        listOf(
            "com.google.android.gms.ads.AdActivity",
            "com.google.android.gms.ads.NotificationHandlerActivity",
            "com.google.android.gms.ads.OutOfContextTestingActivity"
        ).forEach { activityClass ->
            hookClassMethods(activityClass, "onCreate", "onStart", "onResume")
        }
    }
}
