package com.hujiayucc.hook.hooker.sdk

import io.github.libxposed.api.XposedModuleInterface

/** Mintegral */
object Mintegral : SimpleSdkHooker() {
    override fun XposedModuleInterface.PackageReadyParam.onPackageReady() {
        hookClassMethods(
            "com.mbridge.msdk.MBridgeSDK",
            "init",
            "initAsync",
            "preload",
            "preloadFrame",
            "release",
            "setConsentStatus",
            "setDoNotTrackStatus",
            "setCoppaStatus",
            "setAllowAcquireIds",
            "setAllowTransferIdsIfLimit"
        )
        hookClassMethods(
            "com.mbridge.msdk.system.MBridgeSDKImpl",
            "init",
            "initAsync",
            "preload",
            "preloadFrame",
            "release",
            "setConsentStatus",
            "setDoNotTrackStatus",
            "setCoppaStatus",
            "setAllowAcquireIds",
            "setAllowTransferIdsIfLimit"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBridgeSDKFactory",
            "getMBridgeSDK"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBConfiguration",
            "setConsentStatus",
            "setDoNotTrackStatus",
            "setCoppaStatus"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBBannerView",
            "load",
            "loadFromBid",
            "release"
        )
        hookClassMethods(
            "com.mbridge.msdk.interstitialvideo.out.MBInterstitialVideoHandler",
            "load",
            "loadFormSelfFilling",
            "show",
            "isReady",
            "clearVideoCache"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBRewardVideoHandler",
            "load",
            "show",
            "isReady"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBInterstitialHandler",
            "preload",
            "show"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBNativeHandler",
            "load",
            "loadFrame",
            "release",
            "registerView",
            "unregisterView",
            "clearVideoCache",
            "clearCacheByUnitid"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBNativeAdvancedHandler",
            "load",
            "loadByToken",
            "show",
            "showByToken",
            "isReady",
            "release"
        )
        hookClassMethods(
            "com.mbridge.msdk.out.MBSplashHandler",
            "load",
            "preLoadByToken",
            "loadAndShow",
            "loadAndShowByToken",
            "show",
            "isReady",
            "createZoomOutByType"
        )
        listOf(
            "com.mbridge.msdk.activity.MBCommonActivity",
            "com.mbridge.msdk.reward.player.MBRewardVideoActivity",
            "com.mbridge.msdk.interstitial.view.MBInterstitialActivity",
            "com.mbridge.msdk.dycreator.baseview.interactive.InterActiveActivity"
        ).forEach { activityClass ->
            hookClassMethods(activityClass, "onCreate", "onStart", "onResume")
        }
    }
}