package com.hujiayucc.hook.hooker.sdk

import io.github.libxposed.api.XposedModuleInterface

/** TradPlus */
object TradPlus : SimpleSdkHooker() {
    override fun XposedModuleInterface.PackageReadyParam.onPackageReady() {
        hookClassMethods(
            "com.tradplus.ads.open.TradPlusSdk",
            "initSdk",
            "setNeedFirstShowGDPR",
            "setIsCNLanguageLog",
            "setGDPRDataCollection",
            "setLGPDDataCollection",
            "setCCPADoNotSell",
            "isInit"
        )
        hookClassMethods(
            "com.tradplus.ads.base.TradPlus",
            "initSDK",
            "reLoadSDK",
            "checkSDKInit",
            "setIsCNLanguageLog",
            "setGDPRDataCollection",
            "setLGPDConsent",
            "setCCPADoNotSell",
            "setOpenPersonalizedAd",
            "getIsInit"
        )
        hookClassMethods(
            "com.tradplus.ads.base.OpenLoadManager",
            "sendMessage",
            "loadOpenFailed",
            "removeCallBacks",
            "clearOpenBackUpInfo"
        )
        hookClassMethods(
            "com.tradplus.ads.open.splash.TPSplash",
            "loadAd",
            "showAd",
            "isReady",
            "entryAdScenario"
        )
        hookClassMethods(
            "com.tradplus.ads.open.reward.TPReward",
            "loadAd",
            "showAd",
            "isReady",
            "entryAdScenario"
        )
        hookClassMethods(
            "com.tradplus.ads.open.interstitial.TPInterstitial",
            "loadAd",
            "showAd",
            "isReady",
            "entryAdScenario"
        )
        hookClassMethods(
            "com.tradplus.ads.open.banner.TPBanner",
            "loadAd",
            "showAd",
            "isReady",
            "destroy"
        )
        hookClassMethods(
            "com.tradplus.ads.open.nativead.TPNative",
            "loadAd",
            "isReady",
            "entryAdScenario"
        )
        hookClassMethods(
            "com.tradplus.ads.open.nativead.TPNativeAd",
            "registerClickView",
            "registerClickViews",
            "destroy"
        )
        hookClassMethods(
            "com.tradplus.ads.base.adapter.TPBaseAdapter",
            "initAdapter",
            "loadAd",
            "loadCustomAd",
            "isReady",
            "clean",
            "getBiddingToken",
            "getBiddingNetworkInfo",
            "getC2SBidding",
            "C2SBidding"
        )
        hookClassMethods(
            "com.tradplus.ads.base.adapter.banner.TPBannerAdapter",
            "isReady"
        )
        hookClassMethods(
            "com.tradplus.ads.base.adapter.reward.TPRewardAdapter",
            "showAd",
            "isAdsTimeOut",
            "clean"
        )
        hookClassMethods(
            "com.tradplus.ads.base.adapter.interstitial.TPInterstitialAdapter",
            "showAd",
            "clean"
        )
        hookClassMethods(
            "com.tradplus.ads.base.adapter.splash.TPSplashAdapter",
            "showAd",
            "isAdsTimeOut"
        )
        hookClassMethods(
            "com.tradplus.ads.base.adapter.nativead.TPNativeAdapter",
            "isReady",
            "isAdsTimeOut",
            "downloadAndCallback"
        )
        listOf(
            "com.tradplus.ads.mobileads.gdpr.TradplusGDPRAuthActivity",
            "com.tradplus.ads.mobileads.splash.TPSplashActivity",
            "com.tradplus.ads.mobileads.interstitial.TPInterstitialActivity"
        ).forEach { activityClass ->
            hookClassMethods(activityClass, "onCreate", "onStart", "onResume")
        }
    }
}